meta_product_name: "Sets"
meta_title: "Sets - Your physical record collection. Organised, digitally."
meta_description: "The best way to keep your vinyl collection organised digitally. Create setlists, save albums, follow other users."
meta_image: "sets_logo.png" # should exist in `app/assets/images/`
